Repository darkhyper24/blaban, pull requests merged in 2025-04, with the labels that each got.

#17 initial setup for project
  api/blaban3_0.yaml
  blaban/.env
  blaban/config/config.go
  blaban/go.mod
  blaban/go.sum
  blaban/services/api-gateway/go.mod
  blaban/services/auth/go.mod
  blaban/services/menu/go.mod
Labels: enhancement

#18 added configuration for supabase connection for auth service
  .gitignore
  blaban/.env
  blaban/services/auth/cmd/main.go
  blaban/services/auth/go.mod
  blaban/services/auth/go.sum
  blaban/services/auth/internal/db/db.go
Labels: backend

#22 added user and auth services
  auth-service/cmd/main.go
  auth-service/entrypoint.sh
  auth-service/go.mod
  auth-service/go.sum
  auth-service/internal/db/db.go
  auth-service/internal/tokens/token_model.go
  auth-service/internal/tokens/token_service.go
  auth-service/migrations/001_create_refresh_tokens.up.sql
  user-service/cmd/main.go
  user-service/entrypoint.sh
  user-service/go.mod
  user-service/go.sum
  user-service/internal/db/db.go
  user-service/internal/users/user_model.go
  user-service/internal/users/user_service.go
  user-service/migrations/001_create_users.up.sql
Labels: backend

#23 added google oauth functionality
  auth-service/cmd/main.go
  front/arch-project/package-lock.json
  front/arch-project/package.json
  front/arch-project/src/api/auth.ts
  front/arch-project/src/api/config.ts
  front/arch-project/src/context/authContext.tsx
  front/arch-project/src/pages/home.tsx
  front/arch-project/src/pages/login.tsx
  front/arch-project/src/pages/signup.tsx
Labels: backend, frontend

#24 FIX: google oauth correctly redirects to home page
  auth-service/cmd/main.go
Labels: bug, backend

#25 Removed mockdata and fetched data directly from the db in frontend
  Documentation/SRS.md
  front/arch-project/.vite/deps/_metadata.json
  front/arch-project/.vite/deps/package.json
  front/arch-project/src/api/auth.ts
  front/arch-project/src/api/config.ts
  front/arch-project/src/api/menu.ts
  front/arch-project/src/assets/2a4tota.PNG
  front/arch-project/src/assets/2a4toza.PNG
  front/arch-project/src/assets/koshary.PNG
  front/arch-project/src/assets/om-3li.PNG
  front/arch-project/src/components/MenuCategory.tsx
  front/arch-project/src/pages/CategoryItems.tsx
  front/arch-project/src/pages/home.tsx
  front/arch-project/src/styles/CategoryItems.css
  front/arch-project/src/utils/imageUtils.ts
Labels: frontend

#26 Added manager endpoints, and filter endpoint, FInished menu service
  menu-service/cmd/main.go
  menu-service/internal/models/item.go
Labels: backend

#28 Fixed order service and tested it
  order-service/cmd/main.go
  order-service/internal/models/order-item.go
  order-service/internal/models/order.go
  order-service/internal/orders/order_service.go
Labels: backend

#29 checking for health routes and finalized the api-gateway
  api-gateway/cmd/main.go
  auth-service/cmd/main.go
  docker-compose.yml
  front/arch-project/Dockerfile
  front/arch-project/package-lock.json
  front/arch-project/package.json
  front/arch-project/src/api/auth.ts
  front/arch-project/src/context/authContext.tsx
  init-postgres.sh
  menu-service/cmd/main.go
  nginx/nginx.conf
  order-service/cmd/main.go
  payment-service/cmd/main.go
  review-service/cmd/main.go
  user-service/cmd/main.go
Labels: backend

#30 simplified limit reached response and logging IPs
  api-gateway/cmd/main.go
Labels: backend
